version: '3.5'
services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=tdd_rails
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - postgres:/var/lib/postgresql/data:z

  redis:
    image: 'redis:5.0.5'
    command: redis-server
    volumes:
      - 'redis:/data'

  web:
    user: ${USER}
    build:
      context: .
      dockerfile: ./.docker/web/Dockerfile
      args:
        - USER_NAME=${USER:-root}
        - USER_ID=${USER_ID:-1000}
    stdin_open: true
    tty: true
    entrypoint: ["bash", ".docker/web/entrypoint.sh"]
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: tdd_rails
    environment:
      - LC_ALL=en_US.UTF-8
      - REDIS_URL=redis://redis:6379/1
      - REDISCLOUD_URL=redis://redis:6379/1
      - REDIS_PROVIDER=REDISCLOUD_URL
      - RUBY_VERSION=2.6.5
      - RUBY_MAJOR=2.6
      - QT_QPA_PLATFORM=offscreen
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
      - redis
    volumes:
      - .:/tdd_rails
      - gems:/usr/local/bundle

volumes:
  redis:
  postgres:
  gems:
